"""add_chunk_positions_and_chat_citations

Adds the provenance a source-evidence view needs:

* document_chunks.page_start / page_end / char_start / char_end — where a chunk sits in
  its source document. Nullable because chunks indexed before this revision have no
  recorded position (there is no way to recompute one without the original extraction),
  and because only PDFs have pages.
* chat_history.citations_json — the retrieval provenance of a turn, so reloading a
  conversation restores its citations. bot_response is prose; the chunk ids behind it are
  not recoverable from it.

Hand-written rather than autogenerated: `--autogenerate` proposes dropping
`sentimental_resources` and `song_resources`, which have no ORM model and must be kept.

Revision ID: 20260804a001
Revises: 20260729a001
Create Date: 2026-08-04 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260804a001"
down_revision: Union[str, None] = "20260729a001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("document_chunks", sa.Column("page_start", sa.Integer(), nullable=True))
    op.add_column("document_chunks", sa.Column("page_end", sa.Integer(), nullable=True))
    op.add_column("document_chunks", sa.Column("char_start", sa.Integer(), nullable=True))
    op.add_column("document_chunks", sa.Column("char_end", sa.Integer(), nullable=True))
    op.add_column("chat_history", sa.Column("citations_json", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("chat_history", "citations_json")
    op.drop_column("document_chunks", "char_end")
    op.drop_column("document_chunks", "char_start")
    op.drop_column("document_chunks", "page_end")
    op.drop_column("document_chunks", "page_start")
